export const INSERT_TODO_REQUEST = 'INSERT_TODO_REQUEST';

export const LIST_TODOS_REQUEST = 'LIST_TODOS_REQUEST';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';

export const MOVE_TODO_FINISHED_REQUEST = 'MOVE_TODO_FINISHED_REQUEST';

export const MOVE_FINISHED_TODO_REQUEST = 'MOVE_FINISHED_TODO_REQUEST';

export const SEARCH_TODOS_REQUEST = 'SEARCH_TODOS_REQUEST';

export const SEARCH_FINISHED_REQUEST = 'SEARCH_FINISHED_REQUEST';
